server.port: 8080

spring.datasource.populator:
  filename: credentials.sql
  enabled: true

zookeeper:
  url: 127.0.0.1:2181
  url_prefix: 
    juno: 
      queries:
        user: /lisea/juno/user/
        authority: /lisea/juno/authority/
      config: /lisea/juno/config/
      field_names: /lisea/juno/field_names/
    vulcan: /lisea/vulcan/instance_infos/
        
vulcan:
  instance_id: 1
  id_name: snowflakedId
